// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDofjdFjQTQvmM_gbMPq0_y_4h8d1ZwcuI',
    appId: '1:803503947635:android:23f74a9829612edf2d0f06',
    messagingSenderId: '803503947635',
    projectId: 'movei-app-e1086',
    storageBucket: 'movei-app-e1086.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8_g6gbC_zqDmpxyR89z50mf4ALQvOVf8',
    appId: '1:803503947635:ios:0244f387e9faef842d0f06',
    messagingSenderId: '803503947635',
    projectId: 'movei-app-e1086',
    storageBucket: 'movei-app-e1086.firebasestorage.app',
    iosBundleId: 'com.example.moveApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDsczC4wPQdUesu_0taE0pix9ys0nErR8',
    appId: '1:803503947635:web:17be579925c418ec2d0f06',
    messagingSenderId: '803503947635',
    projectId: 'movei-app-e1086',
    authDomain: 'movei-app-e1086.firebaseapp.com',
    storageBucket: 'movei-app-e1086.firebasestorage.app',
    measurementId: 'G-ZLLFNF2HZR',
  );

}